### ISSUE TITLE
fatal: unsafe repository ('/github/workspace' is owned by someone else)

### ISSUE THREAD

**Issue by ravinaik1312** [beatlabs/delete-old-branches-action#20]
A recent GitHub CVE has caused a lot of GitHub Actions including this one to fail with the following error

```
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

Example workflow

```
stale-branches:
    name: Cleanup stale branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.6
        with:
          repo_token: ${{ github.token }}
          date: '1 year ago'
          dry_run: false
          extra_protected_branch_regex: ^(Release|production)$

```
