### ISSUE TITLE
fatal: --unshallow on a complete repository does not make sense

### ISSUE THREAD

**Issue by kunaltyagi** [beatlabs/delete-old-branches-action#26]
Unshallow failure shouldn't cause an error in the action.

Usage: action is a step after actions/checkout and few other actions.
<details>
<summary>Details</summary>

```
Run beatlabs/delete-old-branches-action@v0.0.9
  with:
    repo_token: ***
    date: 3 months ago
    dry_run: true
    delete_tags: false
    extra_protected_branch_regex: ^feature\/([\w\d.]*)\/([\w\d.]*)
    minimum_tags: false
    default_branches: main,master
    exclude_open_pr_branches: true
  env:
    pythonLocation: /opt/hostedtoolcache/PyPy/3.9.12/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/PyPy/3.9.12/x64/bin/lib/pkgconfig
/usr/bin/docker run --name ee6a7d1a83f85403396b8eaa95c52bf39_51a996 --label 72882e --workdir /github/workspace --rm -e pythonLocation -e PKG_CONFIG_PATH -e INPUT_REPO_TOKEN -e INPUT_DATE -e INPUT_DRY_RUN -e INPUT_DELETE_TAGS -e INPUT_EXTRA_PROTECTED_BRANCH_REGEX -e INPUT_MINIMUM_TAGS -e INPUT_DEFAULT_BRANCHES -e INPUT_EXTRA_PROTECTED_TAG_REGEX -e INPUT_EXCLUDE_OPEN_PR_BRANCHES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/rr_perception/rr_perception":"/github/workspace" 72882e:e6a7d1a83f85403396b8eaa95c52bf39
```

</details>
